apiVersion: v1
kind: Template
metadata:
  name: jenkins-slave-nodejs12
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-slave-nodejs12
      labels:
        app: jenkins-slave-nodejs12
    spec:
      dockerImageRepository: jenkins-slave-nodejs12
      lookupPolicy:
        local: false
