apiVersion: v1
kind: Template
metadata:
  name: jenkins-slave-python
parameters:
- name: REPO_BASE
  required: true
- name: ODS_IMAGE_TAG
  required: true
  value: latest
- name: ODS_GIT_REF
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-slave-python
    labels:
      app: jenkins-slave-python
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-slave-python:${ODS_IMAGE_TAG}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: common/jenkins-slaves/python
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/opendevstack/ods-quickstarters.git
      sourceSecret:
        name: cd-user-token
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.rhel7
        from:
          kind: ImageStreamTag
          name: jenkins-slave-base:${ODS_IMAGE_TAG}
      type: Docker
    triggers: []
